### ISSUE TITLE
Numeric posts navigation

### ISSUE THREAD

**Issue by sakinshrestha** [dsgreen/magnetic#17]
* WordPress core has numeric post navigation no need for `magnetic_numeric_posts_navigation()` in `template-tags.php` line 207
* Check: Posts Pagination: https://developer.wordpress.org/reference/functions/the_posts_pagination/

**Comment by dsgreen** [comment]
Resolved: https://github.com/dsgreen/magnetic/commit/2df0a5380cef18482b020e90fdf7b5ddbaa51102
