### ISSUE TITLE
Supporting older WP versions

### ISSUE THREAD

**Issue by sakinshrestha** [dsgreen/magnetic#8]
* Just support at most 3 WordPress versions prior to the current version( ( version 5.2 if 5.5 is latest ) ).
* You can just replace lines 31-35 in header.php with just `wp_body_open();`  or `do_action( 'wp_body_open' );`

**Comment by dsgreen** [comment]
Resolved: https://github.com/dsgreen/magnetic/commit/3a101bd6ff930e0d2db49af798b928f4a4cf70ac
